### ISSUE TITLE
dialog:open-file TypeError

### ISSUE THREAD

**Issue by MadcapJake** [fireball-x/editor-framework#141]
I get this error when I select a file and press `open` inside of the dialog.  I want to send the path back to a panel.
```
TypeError: Cannot assign to read only property 'returnValue' of 1000
    at EventEmitter.<anonymous> (/home/jrusso/github/NitEd/editor-framework/lib/share/dialog.js:25:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter._sendToCore (/home/jrusso/github/NitEd/editor-framework/lib/main/ipc-init.js:43:19)
    at EventEmitter.<anonymous> (/home/jrusso/github/NitEd/editor-framework/lib/main/ipc-init.js:99:15)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/home/jrusso/github/NitEd/bin/electron/resources/atom.asar/browser/api/lib/web-contents.js:89:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at process.<anonymous> (/home/jrusso/github/NitEd/editor-framework/lib/main/index.js:27:12)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process.startup.processFatal.process._fatalException (node.js:223:26)
```

Here's my onclick function:
```js
    'open-file': function() {
      Editor.waitForReply('dialog:open-file',
        {
          filters: [
            { name: 'Nit Source Files', extensions: ['nit'] }
            { name: 'All Files',        extensions: ['*']   }
          ],
          properties: ['openFile']
        },
        function (path) {
          this.set('path', path);
          this.ready();
        }.bind(this)
      );
    }
```

**Comment by MadcapJake** [comment]
Well I was able to workaround this by just getting at electron's dialog via `require('remote').require('dialog)`, so unless this is an actual bug (and not just my poor implementation), you can close this.

**Comment by jwu** [comment]
Hi MadcapJake, 

The dialog:open-file is basically used internal for Editor.dialog. So in page/renderer process, you can just wirte:

```javascript
let result = Editor.Dialog.openFile( ... );
```

Is this work for you?

**Comment by jwu** [comment]
BTW: the `Editor.waitForReply` is a little bit out of document. I will renew the document when I finish 0.4.0 (in my spare time). Currently, if you want to get callback from core/main process, use `Editor.sendRequestToCore( ..., callback )` would be better.

in main-process, you can reply your message above by:

```javascript
Ipc.on( 'foobar:query-from-page', function ( reply, arg1, arg2 ) {
  // NOTE: In the next version, I will move reply to the last argument
  reply( your-argument-back );
} ); 
```

The waitForReply is for another use, in which the reply function need to be an ipc-message. Which made it a little bit complex, an example is just like this:

in some main/renderer process:

```javascript
Editor.waitForReply( 'foobar:query-something', function ( "your, reply, arugments" ) { ... }, timeout-if-you-wish );
```

in other place of main/renderer process:

```javascript
Ipc.on( 'foobar:query-something', function ( sessionID, ... ) {
  // must be `${original-ipc}:reply`, and the first argument must be the sessionID
  Editor.sendToAll( 'foobar:query-something:reply', sessionID, "your, reply, arguments" );
} );
```

Hope this can explain the things. I will write more details for the document once 0.4.0 finished.

**Comment by MadcapJake** [comment]
Yeah that works!  Thanks!  Didn't realize that it was just available right on the Editor global.

**Comment by MadcapJake** [comment]
Ok, I thought maybe `waitForReply` would make it synchronous.  Thanks for the explanation!
