### ISSUE TITLE
How do you manage the docking?

### ISSUE THREAD

**Issue by steelbrain** [fireball-x/editor-framework#26]
Not really a bug but a question. I saw [a photo](https://virtual-host-discourse.global.ssl.fastly.net/uploads/github_atom/optimized/3X/1/4/14cf83ea2dce69338e4a2ce5c37b77f0af00a26f_1_690x461.gif) of this project as a dockable framework on discuss.atom.io and I just wanted to know how do you achieve that behavior?

When items are moved between windows, do you destroy them from one window and recreate them in the other?

**Comment by jwu** [comment]
Yes, when you move a panel from one to another, the panel will first closed in the old window and re-create in the target window. 

Sometimes we have some state in one panel, and wish to restore the when panel re-create, right now this is done by panel's profile system, but I'm going to save and restore some general state such as scrolling position, selecting and in the future version, I'm going to allow user register save/restore method. The save/restore method is different with profile system, the profile system will keep your state in your file-system through io, but save/restore only keep them in the core-level (which is in memory and will gone when you quit your app)

**Comment by steelbrain** [comment]
Awesome, Thanks for the info
