### ISSUE TITLE
benchmark test

### ISSUE THREAD

**Issue by jwu** [fireball-x/editor-framework#28]
I need to known the benchmark for several things:

 - multiple window rendering webGL at the same time.
 - multiple panel rendering webGL at the same time. (different with above, multiple panel share the same window)
 - `<webview>` rendering webGL while its host doing some dom stuff (more about <webview> tag can be found here https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md)
 - ipc messages benchmark tests. 
   - performance for ipc send/recv between main and renderer process
   - performance for ipc forward amongs renderers
   - performance for ipc send/recv in host and webview

All benchmark test should exists in `benchmark/` folder, please create one by yourself.

**Comment by jareguo** [comment]
辛苦凯乐同学这次做了份很棒文档。我个人建议下次类似的 issue，只要把统计结果输出到 terminal 就好。这样以后如果切换了运行环境(例如 windows)，只要管理员运行一次 gulp benchmark，就能做一次检查。
并且以后我们做的所有 benchmark（例如场景读取时间的 benchmark） 也应该是这样来做。这样每个版本发布前，管理员可以验证下新版本的关键性能是否有明显的下降，如果有的话就需要程序员来做出解释。

**Comment by 2youyouo2** [comment]
# Ipc Messages Benchmark:

![ipc-messages](https://cloud.githubusercontent.com/assets/1862402/8088401/9d15dd14-0fd3-11e5-996e-efa863e3ed94.png)

args1: 
```javascript
{
    "message": [
        "test1"
}
```

args2:
```javascript
{
    "message": [
        "test1",
        "aaaaaaaaabbbbbbbcccccccccccddddddddddeeeeeeeeeeeeee",
        "ooooosssssseeeeeeepppppqqqqqqqq",
        "aaaaaaaaabbbbbbbcccccccccccddddddddddeeeeeeeeeeeeee",
        "ooooosssssseeeeeeepppppqqqqqqqq",
        "aaaaaaaaabbbbbbbcccccccccccddddddddddeeeeeeeeeeeeee",
        "ooooosssssseeeeeeepppppqqqqqqqq",
        "aaaaaaaaabbbbbbbcccccccccccddddddddddeeeeeeeeeeeeee",
        "ooooosssssseeeeeeepppppqqqqqqqq",
        "aaaaaaaaabbbbbbbcccccccccccddddddddddeeeeeeeeeeeeee",
        "ooooosssssseeeeeeepppppqqqqqqqq",
        "aaaaaaaaabbbbbbbcccccccccccddddddddddeeeeeeeeeeeeee",
        "ooooosssssseeeeeeepppppqqqqqqqq",
        1112222,
        4444444,
        [
            "fawefawefaw",
            22222222222,
            "fweeeeeeeeee"
        ]
    ]
}
```

**Comment by 2youyouo2** [comment]
# Multiple Window And Mutiple Panels

![multi-webgl](https://cloud.githubusercontent.com/assets/1862402/8088481/384249a8-0fd4-11e5-95df-02e95b549be2.png)

**Comment by jareguo** [comment]
Host to Webview 的性能低到可怕，按 60 fps 算，每一帧最多最多只能发送 15 条消息。但这里有一个让人困惑的地方在于，这个性能开销是 host 部分的，还是 webview 部分的？

**Comment by jwu** [comment]
@2youyouo2 是否能够在 report 里说一下这些 ipc 的测量方法? 特别是 host to webview 和 webview to host.

**Comment by 2youyouo2** [comment]
我测试主要是  webview.send 这句比较花时间，
跟进去后进入到：

```javascript
createHandler = function(m) {
      return function() {
        var args, internal, ref;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        internal = v8Util.getHiddenValue(this, 'internal');
        return (ref = remote.getGuestWebContents(internal.guestInstanceId))[m].apply(ref, args);
      };
    };
```
remote.getGuestWebContents(internal.guestInstanceId) 这句占用比较多时间

```javascript
exports.getGuestWebContents = function(guestInstanceId) {
    var meta;
    meta = ipc.sendSync('ATOM_BROWSER_GUEST_WEB_CONTENTS', guestInstanceId);
    return metaToValue(meta);
  };
```

**Comment by 2youyouo2** [comment]
ipc 测量方法 ：

host to webview：
host 发出消息通知 webview 将开始测试host to webview 并附上 将要发送的消息的条数，webview 重置状态，通知完后记录开始时间。
host开始发送消息，当webview接收到相应条数后，通知host 结束，此时host 记录结束时间。

webview to host:
host 发出消息通知 webview 将开始测试webview to host 并附上 需要发送的消息的条数，通知完后记录开始时间。webview接收到消息后 发送相应条数的消息。
host接收到相应条数的消息后，结束测试，并记录结束时间。

**Comment by 2youyouo2** [comment]
# Normal webgl with dom updating

![normal-webgl-with-dom](https://cloud.githubusercontent.com/assets/1862402/8099192/e7aac1d4-102b-11e5-9124-589862933676.png)

**Comment by 2youyouo2** [comment]
# webview webgl with dom updating (using requestanimationframe)

![webview-webgl-with-dom-requestanimationframe](https://cloud.githubusercontent.com/assets/1862402/8099205/0c873924-102c-11e5-80c1-c8e76fc86546.png)

**Comment by 2youyouo2** [comment]
# webview webgl with dom updating (using setinterval)

![webview-webgl-with-dom-setinterval](https://cloud.githubusercontent.com/assets/1862402/8099222/305cc1a2-102c-11e5-913a-f7ed7b889d88.png)

**Comment by 2youyouo2** [comment]
![image](https://cloud.githubusercontent.com/assets/1862402/8099247/9dc615f4-102c-11e5-9ee0-658b33f2d75a.png)

这里我进行了另一个测试，在webview 里面使用requestAnimationFrame来更新这段代码：

```javascript
    var animate = function () {
            this.stats.begin();

            requestAnimationFrame(animate);

            // gl.clear(gl.COLOR_BUFFER_BIT);
            ctx.clearRect(0, 0, 1, 1);

            this.stats.end();
        }.bind(this);

```
使用了gl.clear(gl.COLOR_BUFFER_BIT); 或 ctx.clearRect(0, 0, 1, 1); 这种代码就会使得webview中的帧率降低。
