### ISSUE TITLE
Feedback from users

### ISSUE THREAD

**Issue by jwu** [fireball-x/editor-framework#38]
**why does event binding use on-click instead of onclick?**

A user without knowing Polymer will confuse with this, because in pure html solution, event binding writing like this:

```html
<h1 onclick="changeText(this)">Click on this text!</h1>
<script>
function changeText(el) { 
    el.innerHTML = "Ooops!";
}
</script>
```

in editor-framework, we do this by use Polymer's event binding, and it should be:

```html
<dom-module id="simple-tag">
  <template>
    <h1 on-click="changeText">Click on this text!</h1>
  </template>
<dom-module>
<script>
  Polymer({
    is: 'simple-tag',
    changeText: function ( event ) {
      el.innerHTML = "Ooops!";
    }
  })
</script>
```

We should add document to introduce the event bindings in editor-framework, shows the format in using them, and reference this document to make them understand where the idea come from: 

https://www.polymer-project.org/1.0/docs/devguide/events.html#annotated-listeners

**Comment by jwu** [comment]
**user ask me how to call a executable programme and wish to have example for this**

Basically we can use child_process, just add one or two demo and documents about it. @nantas

**Comment by nantas** [comment]
Call executable example: https://github.com/fireball-packages/package-examples/tree/master/run-command

event binding documentation: https://github.com/fireball-x/editor-framework/blob/master/docs/editor/event-binding.md
