### ISSUE TITLE
Install error, cannot find gulp-watch

### ISSUE THREAD

**Issue by whoisandie** [fireball-x/editor-framework#43]
Throws an error when the `gulp update-electron` task is run. Cannot find `gulp-watch`. The local and global gulp versions differ.
![screen shot 2015-06-23 at 9 58 04 pm](https://cloud.githubusercontent.com/assets/297132/8321290/ef89544e-19f2-11e5-8165-e016d2e5cf16.png)

**Comment by jwu** [comment]
@whoisandie thanks for your report :D, I fix it in the latest commit. Try it again.

**Comment by whoisandie** [comment]
@jwu Thank you :+1: Also to run the demo, I think the `package-examples` directory has to be committed. Right now, app works fine, but cannot locate the index.html file.

**Comment by nantas** [comment]
Have you tried the following command to install it?
```bash
gulp install-shared-packages
```

**Comment by whoisandie** [comment]
Sorry didn't. Works like a charm :+1:  :)
