### ISSUE TITLE
Make npm package for editor-framework

### ISSUE THREAD

**Issue by areel** [fireball-x/editor-framework#46]
I am using jspm to handle my dependencies, it supports either github repos or npm packages at the moment.
 
It would improve the dependency management if editor-framework was given its own package repo on npmjs.org. This would mean that jspm would be able via npm to pull down dependencies such as fire-path etc.

Regards

Aidan

**Comment by jwu** [comment]
Thanks for your suggestion. I will notice @nantas check for this.

**Comment by nantas** [comment]
Hi @areel 
I have added a bootstrap script to editor-framework and now it utilizing on npm script such as `preinstall`, `install` and `start` for initialization and running.

In your app's dependency you can write:
`"editor-framwork": "fireball-x/editor-framework"`

or run `npm install fireball-x/editor-framework` to enjoy fully automatic installation.

Then just run `npm start` to fire up editor-framework demo.

We will publish editor-framework to npm registry once it's more stable and has more examples.

**Comment by areel** [comment]
Hi Guys, 

Thanks for the response and reaction but when I run ```npm install fireball-x/editor-framework``` I get the following error

```
 npm install fireball-x/editor-framework
\
> editor-framework@0.3.10 preinstall C:\Users\Aidan\node_modules\editor-framework
> node utils/init.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
at  .............................\editor-framework\utils\init.js:14:8
....

npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! editor-framework@0.3.10 preinstall: `node utils/init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the editor-framework@0.3.10 preinstall script 'node utils/init.js'.

```

Regards
Aidan

**Comment by nantas** [comment]
This is my bad, now add `try...catch` block to ensure module detection works.
Please try again @areel
