### ISSUE TITLE
We should make `npm install editor-framework` works

### ISSUE THREAD

**Issue by jwu** [fireball-x/editor-framework#53]
When I try to create a new demo based on editor-framework, I found it really hard to get start. I think most editor-framework users have a background from node.js, so they would love to use editor-framework directly with `npm install`. 

Can this be done in editor-framework? Here are issues and questions I can see from this way:

1. we should publish editor-framework to npm (this should be easy)

2. after npm install it, we should add some CLI commands so that editor-framework can use those commands to create and update the project. My question is: is this possible ?

3. If CLI command is possible after npm install, I wish we can run `editor install` which will trigger editor-framework's gulp commands such as bootstrap, bower install, electron install and anything else. My question here is: can we run gulp file exists in node_modules/editor-framework/... ?

**Comment by nantas** [comment]
now npm install script is fixed, will run a `utils/init.js` script to install devdependencies first. also update `npm-rebuild` task to exclude native modules in devdependencies.
