### ISSUE TITLE
creating or opening a project  only launch a process - but no window

### ISSUE THREAD

**Issue by joseroux** [fireball-x/editor-framework#56]
Hi, all I have after clicking create or open a project, is a process, but no window...
→ on Windows 7 64bit

**Comment by jwu** [comment]
Hi joseroux, 

You can do that, but why not just running a node/io programme?

**Comment by joseroux** [comment]
Hi, not sure what you are saying. This is a visual editor, I need a window! But there's none...

**Comment by jwu** [comment]
Aha, I misunderstand your comment at first. Sorry about that.

So back to the topic, do you have any error report when you running it?

**Comment by nantas** [comment]
@joseroux you can run `fireball.exe` from command line to get console output.

**Comment by joseroux** [comment]
Hi Wu, I think I'm on the wrong project here! Sorry... I'm having problems
with fireball, an html5 game editor... but I had also your project opened
in a tab...

Sorry again.

2015-08-11 10:59 GMT-04:00 Wang Nan <notifications@github.com>:

**Comment by joseroux** [comment]
OK, so it look I was almost at the right place...
