### ISSUE TITLE
Sprite Pixi error

### ISSUE THREAD

**Issue by lucked** [fireball-x/editor-framework#66]
i try draw some sprite using pixi js but dont works 
this code is on ready : function funntion

var texture = PIXI.Texture.fromImage(imageurl);

var bunny = new PIXI.Sprite(texture);

 this.bunny.position.x = 200;
 this.bunny.position.y = 150;

 this.stage.addChild(bunny);

TypeError: Cannot read property 'position' of undefined

texture and bunny return "undefined"

im importing 
<script type="text/javascript" src="app://bower_components/pixi/bin/pixi.min.js"></script>

**Comment by lucked** [comment]
And how open developer tools for debugging
when i open editor framework i see on menu bar a transparent windows named developer tools
why i can see the logs?

**Comment by lucked** [comment]
Pixi Sprite Soved 
now only developer tools i need

**Comment by jwu** [comment]
Hi lucked,

I think pixi problem is not issues relate with editor-framework. Currently, the only thing we support for pixi is in https://github.com/fireball-packages/pixi-grid.

About developer tools, you just click the menu item `Developer/Developer Tools` for your focused window, it will open one.

**Comment by lucked** [comment]
i had clicked but nothing happens developer tools windows are open but transparent

**Comment by jwu** [comment]
Hi Lucked, 

I can not reproduce your problem in both Windows and Mac. The devtools works fine here. Which version of electron are you using.

**Comment by lucked** [comment]
"electron-prebuilt",
  "version": "0.30.0",

http://s14.postimg.org/v9l9bcgv1/developertools.png

why did u stop using fireball.slack?

**Comment by jwu** [comment]
well, i think we already update to 0.33.4 for electron. Maybe that is the problem?

> why did u stop using fireball.slack?

Can't tell more this time, we have a private roadmap recently.
