### ISSUE TITLE
Review dependencies and dev dependencies

### ISSUE THREAD

**Issue by areel** [fireball-x/editor-framework#69]
Looking at package.json, there are a number of dependencies that I think should be dev dependencies instead e.g the various glup dependencies, del , diff are ones that pop out.

Looking at your generator and pure editor-framework the gulp task "make-dist-win", takes the dependencies list and copies it into the resources/app/ so moving dev dependencies into the devDependencies list would help reduce overall size of the packaged application.

Regards

Aidan

**Comment by jwu** [comment]
Hi Aidan,

Those gulp dependencies are used when compiling an editor-framework package.
